### ISSUE TITLE
add collection vendimias

### ISSUE THREAD

**Issue by Japoivvb** [user220205/MongoDB#3]
1. after each vendimia is executed a new document must be saved in a new collection called vendimias with fields
- counter(starting from 1) 
- datetime(showing current date time when vendimia was processed)

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb + details

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by user220205** [comment]
<img width="1132" alt="Screenshot 2024-06-13 at 16 50 31" src="https://github.com/user220205/MongoDB/assets/146854636/48214b1c-58c8-4db8-96ca-6a79a50dbf3f">

**Comment by Japoivvb** [comment]
working as requested, no label set in issue
